### ISSUE TITLE
Arabic - Multiple questions

### ISSUE THREAD

**Issue by Kentoseth** [Orange-OpenSource/conllueditor#14]
Hello/Bonjour.

I am experimenting with https://github.com/inception-project/inception/ at the moment, but there are some drawbacks/quirks due to the nature of the complex morphology and grammar in Arabic. I have a few questions:

 -  Can I create my own PoS and Dependency layers?
 -  Can my PoS layer be at the letter level? Example here: https://corpus.quran.com/treebank.jsp?chapter=1&verse=1&token=1 (the first word 'bism')
 - Can I setup a Phrase layer on top of a Dependency layer? (or stack the phrase layer on top of the other PoS layer)? Example here: https://corpus.quran.com/treebank.jsp?chapter=112&verse=1 (the NS = Nominal Sentence which equates to: PRON + PN + N)
 - Can I make a Dependency layer point to any PoS layer? Example here: https://corpus.quran.com/treebank.jsp?chapter=112&verse=1 (مفعول به = dependency layer pointing back to the verb 'qul')

Thanks.

**Comment by jheinecke** [comment]
Hi,
ConlluEditor is primarily made for editing CoNLL-U files of the Universal Dependencies (UD) project. Multiple syntax layers are not possible in the CoNLL-U format. However you can use a different POS tagset than the one provided by UD. But a POS as assigned to a token, not to a character. 

So for your example `bismi` you have to create a MultiTokenWord (ConlluEditor can do this) `bi` + `smi` in order to assign differnet POS to the preposition `bi`and the noun `smi`. So your first example in CoNLL-U would look like

```
1-2	bi'smi	_	_	_	_	_	_	_	_
1	bi	bi	ADP	_	_	2	case	_	_	
2	'smi	'sm	NOUN	_	Gender=Masc	0	root	_	_
3	l-lahi	l-lah	PROPN	_	Case=Gen	2	nmod	_	_
4	l-raḥmāni	l-raḥmān	ADJ	_	_	3	amod	_	_
5	l-raḥīmi	l-raḥīm	ADJ	_	_	3	amod	_	_
```
(Have alook in the Arabic Treebank for better examples how Arabic can be dealt with within UD)
