### ISSUE TITLE
modify in GUI gives: "INVALID command length «mod 1 »"

### ISSUE THREAD

**Issue by robvanderg** [Orange-OpenSource/conllueditor#18]
When I select a token, and then click the modify button, I get the following error:
INVALID command length «mod 1 »

Where the 1 is based on the index of the token.

**Comment by jheinecke** [comment]
Hi,
sorry for the probably misleading documentation: the "modify" button is only needed to execute a command of the server API directly. This is not what you need here.
To edit a token CTRL-click on the token and a menu sill open.
To attach a token to another head, click the token and than the future head
To make a token the root token, click twice on the token
the commands for the "modify" button (I will rename it to "execute") executes commands for which no other ways exist, like joining two tokens or sentences into one, or to split a token or sentence

**Comment by robvanderg** [comment]
Thanks for your quick reply!, 

So do I understand it correctly that there is currently no way to split or merge a token in the GUI (without using the commands)?

**Comment by jheinecke** [comment]
exactly. I have not had an idea how to do it elegantly. It is not an programming issue, but I'm looking for an easy to use way (where to click to split or join etc)
to join a token with the following type "join 4"  (4 is the id of the node to join)
to split a token "split 4"  (it will double the token and then you can modify form/lemma etc as needed. "split" accepts a third value, namely the character in the form where to split so id the token is "frontdoor" "split 4 5" will split it after the 5th letter. This does not always give the perfect results, since lemmas are split at the same position....

**Comment by robvanderg** [comment]
OK, Thanks again for the quick reply (and the great tool)!
