### ISSUE TITLE
conllueditor windows error

### ISSUE THREAD

**Issue by FedeIure** [Orange-OpenSource/conllueditor#23]
Hi, I'm a windows user trying to install conllueditor. I got this error as in the attachment, yet the tool seems to be working. Could you please tell me what does it affect, and how I could fix it?

Thanks for your time!

Federica
[stderr_output.txt](https://github.com/Orange-OpenSource/conllueditor/files/8859941/stderr_output.txt)

**Comment by jheinecke** [comment]
Hi, you are referring to the first two error messages ? Looks like compilation errors with maven, but since it is working for you, the compilation seems to have worked. I have not yet observed this on my Windows. What java/maven versions do you use ?
If the editor works for you and your conllu-file is correctly modified,  the error could be ignored...

**Comment by Stormur** [comment]
Hi! Everything went fine when compiling with `mvn install -DskipTests`, and conllueditor seems to be working fine after that. The reported error message does not appear to be the complete one printed on screen: there was a list of conllu-like rows highlighted in red before the final message of build failure. 

The java and maven versions are the latest ones, since they have been installed in this occasion.

**Comment by jheinecke** [comment]
I will check why the tests do not work on Windows (pb a path name issue). Please give me nevertheless the java/maven version to be sure that I use the same

**Comment by FedeIure** [comment]
thanks! Here you go: java 8 update 333, java SE development kit 18.0.1.1, maven 3.8.5.

**Comment by jheinecke** [comment]
try the (pre-)release where everything comes compiled and ready to use. The only thing you need to install eventually is java
