### ISSUE TITLE
Feature shortcuts

### ISSUE THREAD

**Issue by NeldaKote** [Orange-OpenSource/conllueditor#28]
Hi!
I am trying to use the shortcuts of features but it is not working. I checked the shortcuts.json, it is in the bin folder. 
Maybe I am trying to use them in the wrong way :(. I edited a word and in the features field I typed :ns for the Number=Sing, but there was not showing any suggestion. For the other fields, it is working.

Can you help me?

Thanks,

**Comment by jheinecke** [comment]
Hi,
I assume you use a shortcut.json file with the option in the following way
```
./bin/conlluedit.sh --shortcuts shortcuts.json  treebank.conllu 5555
```
Shortcuts are not active in the word-edit window, but in the standard tree view (in order to avoid double click to open the edit mode and enter key/values manually).
To use the shortcut you click on the word in question and type the shortcut (.e.g. `:ns`). Since there is a timeout (to allow short and long shotcuts) you must be quick enough (maximal 700 milliseconds).
Since feature-values are not displayed by default, click on `features` first, which displays all featurename/value pairs just underneath the words.
In order to have a list of features to chose from in the word order mode, you must use the option
```
---features  featurefile.txt
```
`featurefile.txt` is either a list of key=values like
```
Number=Sing
Numer=Plur
...
```
or the official https://github.com/UniversalDependencies/tools/blob/master/data/feats.json. If you use this `feats.json` you must also specify the language using ISO 3-letter code
```
--language eng
```

Hope to have helped !
